Repository Wapatah/VPIA, pull requests merged in 2021-02, with the labels that each got.

#111 Create artwork - fixes body input + removes wysiwyg components from infobox on admin side
  SearchService/client/components/artwork_carddeck.jsx
  SearchService/client/components/artwork_results.jsx
  SearchService/client/components/search.jsx
  WikiService/client/components/article.jsx
  WikiService/client/components/edit.jsx
  WikiService/client/components/new.jsx
  package-lock.json
  package.json
Labels: fix

#115 PRs - 114, 113, 112, 102
  HistoryService/package-lock.json
  MainContainer/client/assets/bootstrap.bundle.min.js
  MainContainer/client/assets/images/Eric.jpg
  MainContainer/client/assets/images/FrontConf.jpeg
  MainContainer/client/assets/images/HaidaGwaii.jpg
  MainContainer/client/assets/images/Representing.jpg
  MainContainer/client/assets/images/RoundTable.jpg
  MainContainer/client/assets/images/event_icon.png
  MainContainer/client/assets/maincontainer-style.css
  MainContainer/client/assets/searchservice-style.css
  MainContainer/client/assets/userservice-style.css
  MainContainer/client/components/main/about.jsx
  MainContainer/client/components/main/home.jsx
  MainContainer/client/components/main/landing.jsx
  MainContainer/config/webpack.config.js
  MediaService/package-lock.json
  SearchService/client/components/filters.jsx
  SearchService/client/components/results.jsx
  UserService/client/components/intro_carousel.jsx
  UserService/client/components/login.jsx
  UserService/client/components/user_signup.jsx
  UserService/package-lock.json
  WikiService/client/components/new.jsx
  babel.config.json
  package-lock.json
  package.json
Labels: bug, enhancement, fix

#117 Institution
  HistoryService/client/components/institution.jsx
  MainContainer/client/components/routes.jsx
  WikiService/client/components/article.jsx
  WikiService/client/components/edit.jsx
  WikiService/client/components/infobox.jsx
Labels: enhancement, fix

#120 Institution record - solved original record not saved as archive/refactored new.jsx/improved error handling/made edit.jsx box the same as new.jsx box
  HistoryService/api/archives.js
  WikiService/api/articles.js
  WikiService/client/components/edit.jsx
  WikiService/client/components/new.jsx
Labels: bug, fix
